name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  # Style checks
  style:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install clang-format
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  # Build/run unit tests with cmake
  cmake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install cmake
      run: sudo apt-get install make cmake
    - name: Run Unit Tests
      run: mkdir build && cd build && cmake .. -DPARA_ENABLE_TESTING:bool=on && make && ctest -V
